# Generated by Django 4.2 on 2023-04-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_favoritemovie_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.CharField(max_length=4),
        ),
    ]
