# Generated by Django 4.2 on 2023-04-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_plot_alter_movie_poster_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(max_length=255),
        ),
    ]
